version: '3'

# vars:
#   git_host: download.fastgit.org

#   dl_bin: axel
#   dl_cmd: '{{.dl_bin}}'

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-pre:
    cmds:
      - nix-env -i
          gnumake gcc-wrapper
          diffutils patch
          rsync mercurial darcs

  install-opam-ocaml:
    cmds:
      - nix-env -i opam ocaml

  init-opam:
    vars:
      # https://gitclone.com/github.com/ocaml/opam-repository.git
      # https://hub.fastgit.org/ocaml/opam-repository.git
      DEFAULT_REPO: https://mirrors.sjtug.sjtu.edu.cn/git/opam-repository.git
    cmds:
      - opam init
          --disable-sandboxing
          -y default {{.DEFAULT_REPO}}

  opam-env:
    vars:
      bash_env: eval $(opam env)
      fish_env: eval (opam env)
    cmds:
      - echo '{{.bash_env}}' >> $HOME/.profile
      - echo '{{.fish_env}}' >> $HOME/.config/fish/config.fish

  install-opam-default-pkgs:
    cmds:
      - opam install -y dune utop ocamlfind ocaml-lsp-server
      - opam install -y base core stdio
      # - opam install -y js_of_ocaml js_of_ocaml-compiler js_of_ocaml-lwt js_of_ocaml-ppx

  install-all:
    deps:
      - install-pre
    cmds:
      - task: install-opam-ocaml
      - task: init-opam
      - task: opam-env
      - task: install-opam-default-pkgs
