VERSION 0.6

IMPORT ./Bullseye AS BaseImg
# IMPORT ./Alpine AS BaseImg

IMPORT ./Rust AS Rust

# IMPORT ./Glibc AS Glibs
IMPORT ./Deno AS Deno

base-image:

  FROM BaseImg+img
  DO BaseImg+UPDATE

  DO Rust+INSTALL

  # DO Glibs+BASE
  # DO Glibs+MAIN

  DO Deno+INSTALL

  DO BaseImg+CLEAN

  RUN set -eux \
  ; rustup --version \
  ; cargo --version \
  ; rustc --version \
  ; deno --version

  SAVE IMAGE mooxe/base
