version: '3'

includes:
  nix: ~/.taskfilehub/hubs/nix.yml

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  nix-init-all:
    cmds:

      - task: nix:nix-channel
      - task: nix:nix-channel-update
      - task: nix:nix-mirror
      - task: nix:nix-update

      - nix-env -i go-task

      - nix-env -i
          which-2.21 gnused unzip
          glibc patchelf
