version: '3'

includes:
  apps: ~/.taskfilehub/hubs/apps.yml
  helper: ~/.taskfilehub/hubs/helper.yml

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-shell:
    cmds:
      - nix-env -i
          bash
          fish ncurses
          zsh
          nushell
      - install -d $HOME/.config/fish
      - cp -r ./nushell $HOME/.config

  install-starship:
    cmds:
      - nix-env -i starship
      - echo 'eval "$(starship init bash)"'
        >> $HOME/.bashrc
      - echo 'eval "$(starship init zsh)"'
        >> $HOME/.zshrc
      - echo 'set fish_greeting '''
        >> $HOME/.config/fish/config.fish
      - echo 'starship init fish | source'
        >> $HOME/.config/fish/config.fish
      - install -d $HOME/.cache/starship
      - echo 'mkdir ~/.cache/starship'
        >> $HOME/.config/nushell/env.nu
      - echo 'starship init nu | save ~/.cache/starship/init.nu'
        >> $HOME/.config/nushell/env.nu
      - echo 'source ~/.cache/starship/init.nu'
        >> $HOME/.config/nushell/config.nu

  profile-path:
    cmds:
      - echo '' > ~/.profile
      - echo 'source ~/.profile' >> ~/.bashrc
      - echo 'source ~/.profile' >> ~/.zshrc

      - mkdir -p $HOME/.local/bin

      - task: helper:fn-env-kv
        vars:
          env_key: PATH
          env_value: $PATH:$HOME/.local/bin

  install-editor:
    cmds:
      - nix-env -i neovim
      # helix
      - ln -s $(which nvim) /usr/local/bin/vi
      - ln -s $(which nvim) /usr/local/bin/vim

  install-dltool:
    cmds:
      # aria2
      - nix-env -i axel

  install-sws:
    deps:
      - apps:install-sws
    cmds:
      # - patchelf --print-interpreter /usr/local/bin/static-web-server
      # - patchelf --print-needed /usr/local/bin/static-web-server
      # - patchelf --print-rpath /usr/local/bin/static-web-server
      # - ldd /usr/local/bin/static-web-server

      - task: helper:fn-patchelf-ld
        vars:
          patch_target: /usr/local/bin/static-web-server

  install-all:
    cmds:
      - task: install-shell
      - task: install-starship

      - task: profile-path

      - task: install-editor
      - task: install-dltool

      - task: install-sws
