version: '3'

includes:
  helper: ~/.taskfilehub/hubs/helper.yml

vars:
  # https://github.com/justjavac/dvm/releases
  version_dvm: 1.8.6
  version_deno: 1.28.1

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-dvm:
    vars:
      bin_name: dvm
      repo_name: justjavac/{{.bin_name}}
      bin_version: '{{.version_dvm}}'
      bin_os: x86_64-unknown-linux-gnu
      dl_file: '{{.bin_name}}-{{.bin_os}}.zip'
      url_prefix: '/releases/download'
      url_postfix: '{{.url_prefix}}/v{{.bin_version}}/{{.dl_file}}'
    # https://github.com/justjavac/dvm/releases/download/v1.8.6/dvm-x86_64-unknown-linux-gnu.zip
    cmds:
      - task: helper:fn-download
        vars:
          git_repo: '{{.repo_name}}'
          url_postfix: '{{.url_postfix}}'

      - unzip {{.dl_file}}
      - chmod +x {{.bin_name}}

      - task: helper:fn-patchelf-ld
        vars:
          patch_target: '{{.bin_name}}'

      - mv {{.bin_name}} /usr/local/bin
      - rm -rf {{.dl_file}}

  dvm-env:
    cmds:
      - task: helper:fn-env-kv
        vars:
          env_key: DVM_DIR
          env_value: $HOME/.dvm
      - task: helper:fn-env-kv
        vars:
          env_key: PATH
          env_value: $PATH:$DVM_DIR/bin

  install-deno:
    deps:
      - install-dvm
    cmds:
      - dvm install --no-use {{.version_deno}}

      - task: helper:fn-patchelf-ld
        vars:
          patch_target: $HOME/.dvm/versions/{{.version_deno}}/deno

      - dvm use {{.version_deno}}
      - task: dvm-env

  cli-version:
    cmds:
      - dvm --version
      - deno --version

  install-all:
    cmds:
      - task: install-deno
      - task: cli-version
