version: '3'

vars:
  git_host: download.fastgit.org

  dl_bin: curl
  dl_cmd: '{{.dl_bin}} -O'

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-before:
    cmds:
      - nix-env -i unzip gnused

  install-after:
    cmds:
      - nix-env -e unzip gnused

  # https://github.com/Schniz/fnm/releases
  install-fnm:
    deps:
      - install-before
    vars:
      bin_name: fnm
      git_proj: Schniz/{{.bin_name}}
      bin_version: v1.31.1
      bin_os: linux
      dl_file: '{{.bin_name}}-{{.bin_os}}.zip'
      url_prefix: https://{{.git_host}}/{{.git_proj}}/releases/download
      url: '{{.url_prefix}}/{{.bin_version}}/{{.dl_file}}'
    # https://github.com/Schniz/fnm/releases/download/v1.31.1/fnm-linux.zip
    cmds:
      - '{{.dl_cmd}} {{.url}}'
      - unzip {{.dl_file}}
      - chmod +x {{.bin_name}}
      - mv {{.bin_name}} /usr/local/bin
      - rm -rf {{.dl_file}}

  fnm-env:
    vars:
      bash_env:
        export FNM_NODE_DIST_MIRROR=https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/
      fish_env:
        set FNM_NODE_DIST_MIRROR https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/
    cmds:
      - echo '{{.bash_env}}' >> $HOME/.profile
      - echo '{{.fish_env}}' >> $HOME/.config/fish/config.fish

  install-node:
    deps:
      - install-fnm
      - fnm-env
    env:
      FNM_NODE_DIST_MIRROR: https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/
    vars:
      node_version: v18.11.0
    cmds:
      - fnm install {{.node_version}}

      - fnm env --shell bash >> $HOME/.bashrc
      - fnm env --shell zsh >> $HOME/.zshrc
      - fnm env --shell fish >> $HOME/.config/fish/config.fish

      - patchelf
          --set-interpreter
          $(
            find /nix/store -name ld-linux-x86-64.so.2
          | grep 2.35
          | grep -v debug
          )
          --set-rpath
          $(dirname $(
            find /nix/store -name libstdc++.so.6
          | grep gcc-11.3.0-lib
          | sed -n '1p'
          ))
          $HOME/.local/share/fnm/aliases/default/bin/node

  # https://github.com/oven-sh/bun/releases
  install-bun:
    deps:
      - install-before
    vars:
      bin_name: bun
      git_proj: oven-sh/{{.bin_name}}
      bin_version: v0.2.0
      bin_os: linux-x64
      dl_file_dir: '{{.bin_name}}-{{.bin_os}}'
      dl_file: '{{.dl_file_dir}}.zip'
      url_prefix: https://{{.git_host}}/{{.git_proj}}/releases/download
      url: '{{.url_prefix}}/{{.bin_name}}-{{.bin_version}}/{{.dl_file}}'
    # https://github.com/oven-sh/bun/releases/download/bun-v0.2.0/bun-linux-x64.zip
    cmds:
      - '{{.dl_cmd}} {{.url}}'
      - unzip {{.dl_file}}
      - cd {{.dl_file_dir}}
        ; chmod +x {{.bin_name}}
        ; patchelf
          --set-interpreter
          $(
            find /nix/store -name ld-linux-x86-64.so.2
          | grep 2.35
          | grep -v debug
          ) {{.bin_name}}
        ; mv {{.bin_name}} /usr/local/bin
      - rm -rf {{.dl_file_dir}}
      - rm -rf {{.dl_file}}

  install-all:
    cmds:
      - task: install-node
      - task: install-bun
      - task: install-after
