version: '3'

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  link:
    cmds:
      - if [[ ! -z $HOME/.taskfilehub ]]
        ; then
            rm -rf $HOME/.taskfilehub
        ; fi
      - ln -s $(pwd) $HOME/.taskfilehub

  list:
    cmds:
      - hubs=$(ls ./hubs | tr " " "\n")
        ; for app in $hubs
        ; do
            echo $app | sed "s/.yml$//"
        ; done
