VERSION 0.6

INSTALL:
  COMMAND
  RUN set -eux \
  ; apt-get install -y \
      libxkbcommon-dev \
      libtinfo5

  COPY ./Wasmer/install.sh /root/install.sh

  RUN set -eux \
  # ; curl -O https://raw.fastgit.org/wasmerio/wasmer-install/master/install.sh \
  ; pwd \
  ; sed -i 's/\/\/github.com\/wasmerio/\/\/hub.fastgit.xyz\/wasmerio/g' install.sh \
  ; sh install.sh \
  ; rm install.sh

  RUN set -eux \
  ; rustup target add wasm32-wasi

SHELL:
  COMMAND
  RUN set -eux \
  ; echo '# Wasmer' >> ~/.config/fish/config.fish \
  ; echo 'export WASMER_DIR="/root/.wasmer"' >> ~/.config/fish/config.fish \
  ; echo '[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"' >> ~/.config/fish/config.fish
