version: '3'

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-pre:
    cmds:
      - cp ~/.opam/config ~/.opam/config.bak
      - sed -i '/^download-command/,+4d' ~/.opam/config

  install-post:
    cmds:
      - mv ~/.opam/config.bak ~/.opam/config

  install-pkgs:
    deps:
      - install-pre
    cmds:
      - opam option --global depext=false
      - opam install -y dune utop ocamlfind ocaml-lsp-server
      - opam install -y base core stdio
      # ; opam install -y js_of_ocaml js_of_ocaml-compiler js_of_ocaml-lwt js_of_ocaml-ppx

      - task: install-post
