VERSION 0.6

ENV:
  COMMAND
  ENV ALPINE_GLIBC_PACKAGE_VERSION=2.34-r0

BASE:
  COMMAND
  RUN \
    apk add --no-cache ca-certificates aria2 drill

MAIN:
  COMMAND
  DO +ENV

  RUN set -eux \
  ; drill alpine-pkgs.sgerrand.com @114.114.114.114

  RUN set -eux \
  ; ALPINE_GLIBC_BASE_URL="https://hub.fastgit.xyz/sgerrand/alpine-pkg-glibc/releases/download" \
  ; ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk" \
  ; ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk" \
  ; ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk" \

  ; apk add --no-cache --virtual=.build-dependencies \
  # ; echo \
  #     "-----BEGIN PUBLIC KEY-----\
  #     MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApZ2u1KJKUu/fW4A25y9m\
  #     y70AGEa/J3Wi5ibNVGNn1gT1r0VfgeWd0pUybS4UmcHdiNzxJPgoWQhV2SSW1JYu\
  #     tOqKZF5QSN6X937PTUpNBjUvLtTQ1ve1fp39uf/lEXPpFpOPL88LKnDBgbh7wkCp\
  #     m2KzLVGChf83MS0ShL6G9EQIAUxLm99VpgRjwqTQ/KfzGtpke1wqws4au0Ab4qPY\
  #     KXvMLSPLUp7cfulWvhmZSegr5AdhNw5KNizPqCJT8ZrGvgHypXyiFvvAH5YRtSsc\
  #     Zvo9GI2e2MaZyo9/lvb+LbLEJZKEQckqRj4P26gmASrZEPStwc+yqy1ShHLA0j6m\
  #     1QIDAQAB\
  #     -----END PUBLIC KEY-----" \
  #     | sed 's/   */\n/g' > "/etc/apk/keys/sgerrand.rsa.pub" \
  ; aria2c -d /etc/apk/keys -o sgerrand.rsa.pub \
      https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
  ; aria2c "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
  ; aria2c "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
  ; aria2c "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" \
    # --allow-untrusted
  ; apk add --allow-untrusted --no-cache \
      "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
      "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
      "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" \
  ; rm "/etc/apk/keys/sgerrand.rsa.pub" \

  ; (/usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 "$LANG" || true) \
  ; echo "export LANG=$LANG" > /etc/profile.d/locale.sh \
  ; apk del glibc-i18n \
  # &&  rm "/root/.wget-hsts" \
  ; apk del .build-dependencies \
  ; rm \
      "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
      "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
      "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"
