VERSION 0.6

base-img:
  FROM microdeb/bullseye
  ENV LANG=C.UTF-8
  WORKDIR /root

UPDATE:
  COMMAND
  RUN set -eux \ 
  ; apt-get update \
  ; apt-get upgrade -y

FASTUPDATE:
  COMMAND
  RUN set -eux \ 
  ; apt-fast update \
  ; apt-fast upgrade -y

MIRROR:
  COMMAND
  COPY ./sources.list /etc/apt/sources.list
  DO +UPDATE
  RUN set -eux \ 
  ; apt-get install -y ca-certificates \
  ; sed -i 's/http/https/g' \
      /etc/apt/sources.list

INSTALL:
  COMMAND
  RUN set -eux \ 
  # --no-install-recommends
  ; apt-get install -y \
      wget curl aria2 axel unzip

img:
  FROM +base-img
  DO +MIRROR
  DO +INSTALL

CLEAN:
  COMMAND
  RUN set -eux \
  ; apt-get clean

DEV:
  COMMAND
  DO +UPDATE
