version: '3'

includes:
  helper: ~/.taskfilehub/hubs/helper.yml
  sdkman: ~/.taskfilehub/hubs/sdkman.yml
  scala: ~/.taskfilehub/hubs/language/scala.yml

env:
  SDK_SBT_VERSION:  1.8.0
  SDK_SCALA_VERSION: 3.2.1

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-sbt:
    cmds:
      - task: sdkman:fn-install-sdk
        vars:
          upname: SBT
          lwname: sbt

  install-scala:
    cmds:
      - task: sdkman:fn-install-sdk
        vars:
          upname: SCALA
          lwname: scala

  install-mill:
    cmds:
      - nix-env -i mill

  cli-version:
    cmds:
      - bash -lc "
          sbt --version
        ; scala --version
        ; mill -v
        ; rm -rf ./target
        "

  install-all:
    cmds:
      - task: install-sbt
      - task: install-scala

      - task: scala:scala-mirror
      - task: scala:scala-env

      - task: install-mill

      - task: cli-version
