version: '3'

includes:
  apt: ~/.taskfilehub/hubs/apt.yml
  apps: ~/.taskfilehub/hubs/apps.yml

env:
  PUB_HOSTED_URL: https://mirrors.tuna.tsinghua.edu.cn/dart-pub
  FLUTTER_STORAGE_BASE_URL: https://mirrors.tuna.tsinghua.edu.cn/flutter

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-before:
    cmds:
      - apt install -y
          unzip curl axel
          clang cmake
          pkg-config
          ninja-build
          openjdk-17-jre
      # generate-ninja
      # sdkmanager
      # android-sdk

  install-flutter:
    env:
      PUB_HOSTED_URL: '{{.PUB_HOSTED_URL}}'
      FLUTTER_STORAGE_BASE_URL: '{{.FLUTTER_STORAGE_BASE_URL}}'
      TAR_OPTIONS: '--no-same-owner'
      # FLUTTER_GIT_URL: https://gitclone.com/github.com/flutter/flutter.git
      FLUTTER_GIT_URL: https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
      REPO_OS_OVERRIDE: linux
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      ANDROID_SDK_ROOT: $HOME/.sdk_root
    vars:
      # https://developer.android.com/studio#command-tools
      cmdline_tools_version: 9477386
      cmdline_tools_zip: commandlinetools-linux-{{.cmdline_tools_version}}_latest.zip
      cmdline_tools_url: https://dl.google.com/android/repository/{{.cmdline_tools_zip}}?hl=zh-cn
    cmds:
      # - set -gx PATH $PATH:$HOME/.flutter/bin
      - git clone
          -b flutter-3.7-candidate.29
          --depth=1
          $FLUTTER_GIT_URL
          ~/.flutter
      - axel '{{.cmdline_tools_url}}'
        ; unzip {{.cmdline_tools_zip}}
        ; rm -rf {{.cmdline_tools_zip}}
        ; mv cmdline-tools $HOME/.cmdline-tools
      - mkdir -p $HOME/.sdk_root

      # - set -gx PATH $PATH:$HOME/.cmdline-tools/bin

      - export PATH=$PATH:$HOME/.cmdline-tools/bin
        ; sdkmanager
          --sdk_root=$ANDROID_SDK_ROOT
          --update
        ; yes | sdkmanager
          --sdk_root=$ANDROID_SDK_ROOT
          --install 'cmdline-tools;latest'

      - rm -rf $HOME/.cmdline-tools

      # - set -gx PATH $PATH:$HOME/.sdk_root/cmdline-tools/latest/bin
      - export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        ; sdkmanager
          --sdk_root=$ANDROID_SDK_ROOT
          --update
        ; yes | sdkmanager
          --sdk_root=$ANDROID_SDK_ROOT
          --install
            'platforms;android-33'
            'platform-tools'
            'build-tools;30.0.3'

      # --no-https
      # --proxy_host
      # --proxy_port
      # https://flutter.cn/community/china
      # 东软信息学院
      # mirrors.neusoft.edu.cn 80
      # 北京化工大学
      # ubuntu.buct.edu.cn/ubuntu.buct.cn 80
      # 中国科学院开源协会
      # mirrors.opencas.cn/mirrors.opencas.org/mirrors.opencas.ac.cn 80
      # 上海GDG镜像服务器
      # sdk.gdgshanghai.com 8000
      # 电子科技大学
      # mirrors.dormforce.net 80
      # 腾讯Bugly
      # android-mirror.bugly.qq.com 8080
      - export PATH=$PATH:$HOME/.flutter/bin
        ; flutter config --android-sdk $ANDROID_SDK_ROOT
        ; yes | flutter doctor --android-licenses

  flutter-path:
    vars:
      PATH: '$PATH:$HOME/.flutter/bin:$HOME/.sdk_root/cmdline-tools/latest/bin'
    cmds:

      - echo 'export PATH={{.PATH}}'
          >> $HOME/.bashrc
      - echo 'export PUB_HOSTED_URL={{.PUB_HOSTED_URL}}'
          >> $HOME/.bashrc
      - echo 'export FLUTTER_STORAGE_BASE_URL={{.FLUTTER_STORAGE_BASE_URL}}'
          >> $HOME/.bashrc

      - mkdir -p $HOME/.config/fish

      - echo 'set -gx PATH {{.PATH}}'
        | tee $HOME/.config/fish/config.fish
      - echo 'set -gx PUB_HOSTED_URL {{.PUB_HOSTED_URL}}'
        | tee $HOME/.config/fish/config.fish
      - echo 'set -gx FLUTTER_STORAGE_BASE_URL {{.FLUTTER_STORAGE_BASE_URL}}'
        | tee $HOME/.config/fish/config.fish

  init-gradle:
    cmds:
      - mkdir -p $HOME/.gradle
      - cp ./init.gradle $HOME/.gradle

  flutter-status:
    deps:
      - apt:apt-clean
    cmds:
      - export PATH=$PATH:$HOME/.flutter/bin
        ; flutter doctor
        ; flutter --version
        ; dart --version

  install-all:
    deps:
      - install-before
    cmds:
      - task: install-flutter
      - task: flutter-path

      - task: apps:install-sws
      - task: init-gradle

      - task: flutter-status
