version: '3'

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  rust-env:
    vars:
      bash_env:
        export RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
        export PATH=$PATH:$HOME/.cargo/bin
      fish_env:
        set RUSTUP_UPDATE_ROOT https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
        set PATH $PATH:$HOME/.cargo/bin
    cmds:
      - echo '{{.bash_env}}' >> $HOME/.profile
      - echo '{{.fish_env}}' >> $HOME/.config/fish/config.fish
      - install -D cargo.config $HOME/.cargo/config

  install-rust:
    deps:
      - rust-env
    cmds:
      - nix-env -i rustup
      - env
          RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup
          rustup install stable

  install-cargo-update:
    cmds:
      - nix-shell
          -p clang pkg-config openssl
          --run 'cargo install cargo-update'
      - nix-shell
          -p clang perl openssl
          --run 'cargo install cargo-generate'
