version: '3'

includes:
  sdkman: ~/.taskfilehub/hubs/sdkman.yml

env:
  SDK_MAVEN_VERSION: 3.8.6
  SDK_GRADLE_VERSION: 7.6

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-maven:
    cmds:
      - task: sdkman:fn-install-sdk
        vars:
          upname: MAVEN
          lwname: maven

  install-gradle:
    cmds:
      - task: sdkman:fn-install-sdk
        vars:
          upname: GRADLE
          lwname: gradle

  cli-version:
    cmds:
      - bash -lc "
          mvn --version
          | sed -n '1p'
          | awk '{print \$1 \" \" \$2 \" \" \$3}'
        ; gradle --version
          | sed -n '3p'
        "

  install-all:
    cmds:
      - task: install-maven
      - task: install-gradle

      - task: cli-version
