version: '3'

vars:
  proj_name: helloapp

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  create:
    cmds:
      - flutter create {{.proj_name}}

  source:
    cmds:
      - cp -r ./source/* ./{{.proj_name}}

  build-apk:
    cmds:
      - cd {{.proj_name}}
        ; flutter build apk
    # ; flutter build -v apk

  build-web:
    cmds:
      - cd {{.proj_name}}
        ; flutter build web

  run-web:
    cmds:
      - cd {{.proj_name}}/build/web
        ; sws -d .
            -a 0.0.0.0
            -p 8000

  rm:
    cmds:
      - rm -rf {{.proj_name}}

  release:
    cmds:
      - mkdir -p ./release/{{.proj_name}}
      - cp ./{{.proj_name}}/build/app/outputs/flutter-apk/app-release.apk
          ./release/{{.proj_name}}/app-release.apk
