VERSION 0.6

base-img:
  FROM alpine:3.15
  ENV LANG=C.UTF-8
  WORKDIR /root

DNS:
  COMMAND
  COPY ./resolv.conf /etc/resolv.conf

img:
  FROM +base-img
  # DO +DNS

UPDATE:
  COMMAND
  RUN set -eux \ 
  ; sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' \
      /etc/apk/repositories \
  ; apk update \
  ; apk upgrade
