version: '3'

includes:
  helper: ~/.taskfilehub/hubs/helper.yml
  patchelf: ~/.taskfilehub/hubs/patchelf.yml
  scala: ~/.taskfilehub/hubs/language/scala.yml

  mill: ./mill.yml
  cs-cache: ./cs-cache.yml

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-coursier:
    vars:
      bin_rename: cs
      repo_name: coursier/coursier
      bin_version: 2.1.0-RC2
      bin_os: x86_64-pc-linux
      bin_name: '{{.bin_rename}}-{{.bin_os}}'
      dl_file: '{{.bin_name}}.gz'
      url_prefix: '/releases/download'
      url_postfix: '{{.url_prefix}}/v{{.bin_version}}/{{.dl_file}}'
    cmds:
      - task: helper:fn-download
        vars:
          git_repo: '{{.repo_name}}'
          url_postfix: '{{.url_postfix}}'

      - gzip -d {{.dl_file}}
      - mv {{.bin_name}} {{.bin_rename}}
      - chmod +x {{.bin_rename}}
      - mv {{.bin_rename}} /usr/local/bin

  patch-coursier:
    cmds:
      - task: patchelf:auto-patch
        vars:
          rpath_env: |
            libz_path:
              find_path: /nix/store
              find_name: libz.so.1
              grep_option: zlib-1.2.13
          bin_path: /usr/local/bin/cs

  setup-coursier:
    deps:
      - cs-cache:cache-all
    cmds:
      - axel https://raw.fastgit.org/coursier/jvm-index/master/index.json
      # - cs java --available --jvm-index ./index.json
      - cs setup
          --yes
          --jvm graalvm-java17:22.3.0
          --jvm-index ./index.json
      - rm ./index.json

  coursier-env:
    cmds:
      - echo $(grep JAVA_HOME ~/.profile | sed -e 's/export/set -gx/' -e 's/=/ /')
        >> $HOME/.config/fish/config.fish
      - echo 'set -gx PATH $PATH:$JAVA_HOME/bin'
        >> $HOME/.config/fish/config.fish
      - echo 'eval (cs install --env)'
        >> $HOME/.config/fish/config.fish

  patchelf-java:
    # $HOME/.cache/coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java17-linux-amd64-22.3.0.tar.gz/graalvm-ce-java17-22.3.0
    vars:
      cache_dir_root: $HOME/.cache/coursier/arc
      gihub_cache_dir: '{{.cache_dir_root}}/https/github.com'
      repo_name: graalvm/graalvm-ce-builds
      url_prefix: /releases/download
      bin_version_tag: 22.3.0
      bin_version: vm-{{.bin_version_tag}}
      bin_os: linux-amd64
      dl_file: graalvm-ce-java17-{{.bin_os}}-{{.bin_version_tag}}.tar.gz
      cache_dir: graalvm-ce-java17-{{.bin_version_tag}}
      JAVA_HOME: '{{.cache_dir_root}}/https/github.com/{{.repo_name}}{{.url_prefix}}/{{.bin_version}}/{{.dl_file}}/{{.cache_dir}}'
    cmds:
      - task: patchelf:auto-patch
        vars:
          rpath_env: |
            libz_path:
              find_path: /nix/store
              find_name: libz.so.1
              grep_option: zlib-1.2.13
            libjli_path:
              find_path: {{.JAVA_HOME}}
              find_name: libjli.so
              grep_option: '-v grep'
          # bin_path:
          bin_dir: '{{.JAVA_HOME}}/bin'

  patchelf-coursier:
    cmds:
      - task: patchelf:auto-patch
        vars:
          rpath_env: |
            libz_path:
              find_path: /nix/store
              find_name: libz.so.1
              grep_option: zlib-1.2.13
          bin_dir: $HOME/.local/share/coursier/bin

  cli-version:
    cmds:
      - java --version
      - cs version
      - sbt --version
      - scala --version
      - task: helper:fn-bash-lc
        vars:
          commands: mill -v
      - rm -rf ./target
      - rm -rf ./out

  install-all:
    cmds:
      - task: install-coursier
      - task: patch-coursier
      - task: setup-coursier
      - task: coursier-env

      - task: patchelf-java
      - task: patchelf-coursier

      - task: scala:scala-mirror
      - task: scala:scala-env

      - task: mill:install-all

      - task: cli-version
