version: '3'

includes:
  helper: ~/.taskfilehub/hubs/helper.yml

vars:
  RUSTUP_DIST_SERVER: https://mirrors.tuna.tsinghua.edu.cn/rustup

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  rust-env:
    cmds:
      - task: helper:fn-env-kv
        vars:
          env_key: RUSTUP_UPDATE_ROOT
          env_value: '{{.RUSTUP_DIST_SERVER}}'
      - task: helper:fn-env-kv
        vars:
          env_key: PATH
          env_value: $PATH:$HOME/.cargo/bin

      - install -D cargo.config $HOME/.cargo/config

  install-rust:
    deps:
      - rust-env
    cmds:
      - nix-env -i rustup
      - env
          RUSTUP_DIST_SERVER={{.RUSTUP_DIST_SERVER}}
          rustup install stable

  install-cargo-update:
    cmds:
      - nix-shell
          -p clang pkg-config openssl
          --run 'cargo install cargo-update'
      - nix-shell
          -p clang perl openssl
          --run 'cargo install cargo-generate'

  cli-version:
    cmds:
      - rustup --version
        | sed -n '1p'
      - rustc --version

  install-all:
    deps:
      - install-rust
    cmds:
      - task: install-cargo-update

      - task: cli-version
