version: '3'

includes:
  helper: ~/.taskfilehub/hubs/helper.yml
  patchelf: ~/.taskfilehub/hubs/patchelf.yml

vars:
  # https://github.com/wasmerio/wapm-cli
  version_wapm: 0.5.9

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-before:
    cmds:
      - rustup target add wasm32-wasi
      - rustup target add wasm32-unknown-unknown
      - rustup target add wasm32-unknown-emscripten

  # https://github.com/rustwasm
  # https://rustwasm.github.io/wasm-pack/
  # https://rustwasm.github.io/docs/book/introduction.html
  install-wasm:
    cmds:
      # - nix-shell
      #     -p clang perl openssl
      #     --run 'cargo install wasm-pack'
      - nix-env -i wasm-pack
      - nix-env -i wasmtime wasmer

  install-wapm:
    # https://github.com/wasmerio/wapm-cli/releases/download/v0.5.6/wapm-cli-linux-amd64.tar.gz
    vars:
      bin_name: wapm
      repo_name: wasmerio/{{.bin_name}}-cli
      bin_version: '{{.version_wapm}}'
      bin_os: linux-amd64
      dl_file: '{{.bin_name}}-cli-{{.bin_os}}.tar.gz'
      url_prefix: '/releases/download'
      url_postfix: '{{.url_prefix}}/v{{.bin_version}}/{{.dl_file}}'
    cmds:
      - task: helper:fn-download
        vars:
          git_repo: '{{.repo_name}}'
          url_postfix: '{{.url_postfix}}'

      - mkdir -p {{.bin_name}}
        ; mv {{.dl_file}} {{.bin_name}}
      - cd {{.bin_name}}
        ; tar xvf {{.dl_file}}
        ; chmod +x bin/wa*
        ; sed
            -i '1s/^.*$/#!\/usr\/bin\/env bash/'
            bin/wax

      - task: patchelf:auto-patch
        vars:
          bin_path: '{{.bin_name}}/bin/{{.bin_name}}'

      - mv {{.bin_name}}/bin/wa* /usr/local/bin
      - rm -rf {{.bin_name}}

  cli-version:
    cmds:
      - wasmer --version
      - wasmtime --version
      - wapm --version

  install-all:
    deps:
      - install-before
    cmds:
      - task: install-wasm
      - task: install-wapm

      - task: cli-version
