VERSION 0.6

base-img:
  # FROM microdeb/bullseye
  FROM ubuntu:jammy
  ENV LANG=C.UTF-8
  WORKDIR /root

UPDATE:
  COMMAND
  RUN set -eux \
  ; apt-get update \
  ; apt-get upgrade -y

FASTUPDATE:
  COMMAND
  RUN set -eux \
  ; apt-fast update \
  ; apt-fast upgrade -y

MIRROR:
  COMMAND

  # COPY ./sources.list /etc/apt/sources.list
  RUN set -eux \
  ; sed -i \
      's/\(archive\|security\).ubuntu.com/mirrors.aliyun.com/g' \
      /etc/apt/sources.list

  DO +UPDATE

  RUN set -eux \
  ; apt-get install -y ca-certificates \
  ; sed -i 's/http/https/g' \
      /etc/apt/sources.list

INSTALL:
  COMMAND

  RUN set -eux \
  ; apt-get install -y pkg-config

  RUN set -eux \
  ; apt-get install -y --no-install-recommends \
      wget curl aria2 axel unzip

img:
  FROM +base-img
  DO +MIRROR
  DO +UPDATE

CLEAN:
  COMMAND
  RUN set -eux \
  ; apt-get autoremove -y \
  ; apt-get clean

PROFILE:
  COMMAND
  RUN set -eux \
  ; echo '' > ~/.profile \
  ; echo 'source ~/.profile' >> ~/.bashrc

PATH:
  COMMAND
  RUN set -eux \
  ; mkdir -p $HOME/.local/bin \
  ; echo 'export PATH=$PATH:$HOME/.local/bin' \
      >> $HOME/.profile

ET:
  COMMAND

  RUN set -eux \
  ; apt install -y software-properties-common \
  ; add-apt-repository ppa:jgmath2000/et \
  ; apt install -y ssh et
