version: '3'

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-deno:
    cmds:
      - nix-env -i deno

  cli-version:
    cmds:
      - deno --version

  install-all:
    cmds:
      - task: install-deno
      - task: cli-version
