version: '3'

vars:
  ContainerName: nix_g_go
  ImageName: mooxe/{{.ContainerName}}

includes:
  image:
    taskfile: ~/.taskfilehub/hubs/image.yml
    vars:
      ContainerName: '{{.ContainerName}}'
      ImageName: '{{.ImageName}}'

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  build:
    cmds:
      - if [ -d './resource/.taskfilehub' ]
        ; then
          rm -rf ./resource/.taskfilehub
        ; fi
      - cp -R ~/.taskfilehub ./resource
      - task: image:build:build

  run-dev:
    cmds:
      - task: image:run:run-dev
        vars:
          run_option: '-v ~/.taskfilehub:/root/.taskfilehub'

  run:
    cmds:
      - task: image:run:run
