version: '3'

vars:
  ContainerName: nix_base
  ImageName: mooxe/{{.ContainerName}}

includes:
  image:
    taskfile: ~/.taskfilehub/hubs/image.yml
    vars:
      ContainerName: '{{.ContainerName}}'
      ImageName: '{{.ImageName}}'
  taskhub: ~/.taskfilehub/hubs/taskfilehub.yml
  taskbin: ~/.taskfilehub/hubs/taskbin.yml

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  build:
    cmds:
      - task: taskhub:files
      - task: image:build:build
      # - task: image:build:build-with-cache

  run-dev:
    cmds:
      - task: image:run:run-dev
        vars:
          run_option: '-v ~/.taskfilehub:/root/.taskfilehub'

  run:
    cmds:
      - task: image:run:run

  # https://hydra.nixos.org/build/201045031
  base-img:
    vars:
      build_id: 201045031
    cmds:
      - aria2c
          -o nix.tar.gz
          https://hydra.nixos.org/build/{{.build_id}}/download/1/image.tar.gz
      - podman load -i ./nix.tar.gz
      - rm ./nix.tar.gz
