version: '3'

vars:
  ContainerName: nix_rust
  ImageName: mooxe/{{.ContainerName}}

includes:
  image:
    taskfile: ../../tasklib/image.yml
    vars:
      ContainerName: '{{.ContainerName}}'
      ImageName: '{{.ImageName}}'
  tasklib: ../../tasklib/tasklib.yml

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  build:
    deps:
      - tasklib:tasklib
    cmds:
      - task: image:build:build

  run-dev:
    cmds:
      - task: image:run:run-dev

  run:
    cmds:
      - task: image:run:run
