VERSION 0.6

IMPORT ./Bullseye AS BaseImg
IMPORT ./Bullseye/DEV AS BaseDev

IMPORT ./Rust AS Rust
IMPORT ./Go AS Go

IMPORT ./Deno AS Deno
IMPORT ./Node AS Node

IMPORT ./Wasm AS Wasm

IMPORT ./Sdkman AS Sdkman
IMPORT ./Ocaml AS Ocaml

IMPORT ./MvgsColmap AS MvgsColmap

base-image:

  FROM BaseImg+img

  DO BaseImg+PROFILE
  DO BaseImg+PATH

  DO Rust+INSTALL
  DO Rust+MASK

  DO Deno+INSTALL
  DO Deno+INSTALL_DVM

  DO Deno+BUN

  DO BaseImg+CLEAN

  RUN set -eux \
  ; rustup --version \
  ; cargo --version \
  ; rustc --version \
  ; deno --version

  SAVE IMAGE --push mooxe/base

dev-image:

  # FROM mooxe/base
  FROM +base-image

  ENV TZ=Asia/Shanghai

  RUN set -eux \
  ; mkdir -p $HOME/.config/nushell

  DO BaseDev+APTFAST

  DO BaseDev+SHELLEDITOR
  DO BaseDev+NU
  # DO Rust+MIRRORO

  DO BaseDev+STARSHIP
  # DO BaseDev+OHMYPOSH

  DO BaseDev+PATH
  DO BaseDev+SWS

  DO BaseImg+CLEAN

  SAVE IMAGE --push mooxe/dev

go-image:

  # FROM mooxe/dev
  FROM +dev-image

  DO Go+G_INSTALL
  DO Go+GO_INSTALL

  DO BaseImg+CLEAN

  SAVE IMAGE --push mooxe/go

node-image:

  # FROM mooxe/dev
  FROM +dev-image

  DO Node+INSTALL

  SAVE IMAGE --push mooxe/node

wasm-image:

  # FROM mooxe/dev
  FROM +dev-image

  DO Wasm+WASM_BASE
  DO Wasm+WASMER_INSTALL
  DO Wasm+WASMTIME_INSTALL
  DO Wasm+RUSTWASMC_INSTALL

  DO Rust+MIRRORT
  DO Wasm+WASM_BINDGEN_INSTALL

  DO Wasm+WASMER_SHELL_DEV
  DO Wasm+WASMTIME_SHELL_DEV

  DO BaseImg+CLEAN

  SAVE IMAGE --push mooxe/wasm

sdkman-image:

  FROM +dev-image

  DO Sdkman+ALL

  SAVE IMAGE --push mooxe/sdkman

ocaml-image:

  FROM +dev-image

  DO Ocaml+IMAGE

  RUN set -eux \
  ; opam --version \
  ; eval $(opam env) \
  ; ocaml --version

  SAVE IMAGE --push mooxe/ocaml

mvgscolmap-image:

  # FROM +base-image
  FROM +dev-image

  DO MvgsColmap+OPENMVG_INSTALL
  DO MvgsColmap+OPENMVS_INSTALL

  DO BaseImg+CLEAN

  SAVE IMAGE --push mooxe/mvgscolmap
