VERSION 0.6

IMPORT ../ AS BaseImg

NU:
  COMMAND

  RUN set -eux \
  ; apt-fast install -y pkg-config libssl-dev

  RUN set -eux \
  ; cargo install nu

APTFAST:
  COMMAND
  RUN set -eux \
  ; wget https://hub.fastgit.xyz/ilikenwf/apt-fast/archive/master.zip \
  ; unzip master.zip \
  ; cd apt-fast-master \
  ; cp apt-fast /usr/local/sbin \
  ; chmod +x /usr/local/sbin/apt-fast \
  ; cp apt-fast.conf /etc \
  ; cd .. \
  ; rm -rf master.zip apt-fast-master

  RUN set -eux \
  ; apt-get install -y ncurses-bin

  DO BaseImg+FASTUPDATE

OHMYPOSH:
  COMMAND

  RUN set -eux \
  ; wget https://hub.fastgit.xyz/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 \
      -O /usr/local/bin/oh-my-posh \
  ; chmod +x /usr/local/bin/oh-my-posh \

  ; mkdir ~/.poshthemes \
  ; wget https://hub.fastgit.xyz/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip \
      -O ~/.poshthemes/themes.zip \
  ; unzip ~/.poshthemes/themes.zip -d ~/.poshthemes \
  ; chmod u+rw ~/.poshthemes/*.json \
  ; rm ~/.poshthemes/themes.zip
