VERSION 0.6

IMPORT ../ AS BaseImg

NU:
  COMMAND

  RUN set -eux \
  ; cargo install nu

SHELLEDITOR:
  COMMAND

  RUN set -eux \
  ; apt-fast install -y git fish zsh \
  ; apt-fast install -y vim neovim

APTFAST:
  COMMAND
  RUN set -eux \
  ; wget https://hub.fastgit.xyz/ilikenwf/apt-fast/archive/master.zip \
  ; unzip master.zip \
  ; cd apt-fast-master \
  ; cp apt-fast /usr/local/sbin \
  ; chmod +x /usr/local/sbin/apt-fast \
  ; cp apt-fast.conf /etc \
  ; cd .. \
  ; rm -rf master.zip apt-fast-master

  RUN set -eux \
  ; apt-get install -y ncurses-bin

  DO BaseImg+FASTUPDATE

PATH:
  COMMAND
  RUN set -eux \
  ; mkdir -p $HOME/.local/bin \
  ; mkdir -p $HOME/.config/fish \
  ; echo 'set PATH $PATH:$HOME/.local/bin' \
      >> $HOME/.config/fish/config.fish

STARSHIP:
  COMMAND

  ENV STARSHIP_VERSION=1.9.1
  ENV STARSHIP_DL_NAME=starship-x86_64-unknown-linux-gnu.tar.gz

  RUN set -eux \
  # ; cargo install starship
  ; axel "https://hub.fastgit.xyz/starship/starship/releases/download/v${STARSHIP_VERSION}/${STARSHIP_DL_NAME}" \
  ; tar xvf $STARSHIP_DL_NAME \
  ; mv starship $HOME/.local/bin \
  ; rm $STARSHIP_DL_NAME

  RUN set -eux \
  ; mkdir -p $HOME/.config/nushell

  COPY ./Bullseye/DEV/nushell/* /root/.config/nushell/


  RUN set -eux \
  ; echo 'eval "$(starship init bash)"' \
      >> $HOME/.bashrc \
  ; echo 'eval "$(starship init zsh)"' \
      >> $HOME/.zshrc \
  ; echo "set fish_greeting ''" \
      >> $HOME/.config/fish/config.fish \
  ; echo 'starship init fish | source' \
      >> $HOME/.config/fish/config.fish \
  ; mkdir -p $HOME/.cache/starship \
  ; mkdir -p $HOME/.config/nushell \
  ; echo 'let-env PATH = ($env.PATH | append "$HOME/.local/bin")' \
      >> $HOME/.config/nushell/login.nu \
  ; starship init nu \
      >> $HOME/.cache/starship/init.nu \
  ; echo "source ~/.cache/starship/init.nu" \
      >> $(nu -l -c 'echo $nu.config-path')

# OHMYPOSH:
#   COMMAND

#   RUN set -eux \
#   ; wget https://hub.fastgit.xyz/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 \
#       -O /usr/local/bin/oh-my-posh \
#   ; chmod +x /usr/local/bin/oh-my-posh \

#   ; mkdir ~/.poshthemes \
#   ; wget https://hub.fastgit.xyz/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip \
#       -O ~/.poshthemes/themes.zip \
#   ; unzip ~/.poshthemes/themes.zip -d ~/.poshthemes \
#   ; chmod u+rw ~/.poshthemes/*.json \
#   ; rm ~/.poshthemes/themes.zip

#   RUN set -eux \
#   ; echo 'eval "$(oh-my-posh --init --shell bash --config $HOME/.poshthemes/ys.omp.json)"' \
#       >> $HOME/.bashrc \
#   ; echo 'eval "$(oh-my-posh --init --shell zsh --config $HOME/.poshthemes/ys.omp.json)"' \
#       >> $HOME/.zshrc \
#   ; mkdir -p $HOME/.config/fish \
#   ; echo "set fish_greeting ''" \
#       >> $HOME/.config/fish/config.fish \
#   ; echo 'oh-my-posh --init --shell fish --config $HOME/.poshthemes/ys.omp.json | source' \
#       >> $HOME/.config/fish/config.fish

SWS:
  COMMAND

  ENV SWS_VERSION=2.10.0
  ENV SWS_BIN=static-web-server
  ENV SWS_ALIAS=sws
  ENV SWS_DL_FILE_DIR=$SWS_BIN-v${SWS_VERSION}-x86_64-unknown-linux-gnu
  ENV SWS_DL_FILE=${SWS_DL_FILE_DIR}.tar.gz

  RUN set -eux \
  ; aria2c "https://hub.fastgit.xyz/joseluisq/${SWS_BIN}/releases/download/v${SWS_VERSION}/${SWS_DL_FILE}" \
  ; tar xvf ./$SWS_DL_FILE \
  ; cp ./$SWS_DL_FILE_DIR/$SWS_BIN $HOME/.local/bin \
  ; ln -s $HOME/.local/bin/$SWS_BIN $HOME/.local/bin/sws \
  ; rm -rf ./${SWS_BIN}*
