VERSION 0.6

INSTALL:
  COMMAND

  # ENV FNM_VERSION=1.31.0
  #   --skip-shell
  # curl -o- https://fnm.vercel.app/install | bash

  RUN set -eux \

#   ; aria2c \
#       # "https://github.com/Schniz/fnm/releases/download/v${FNM_VERSION}/fnm-linux.zip" \
#       "https://hub.fastgit.xyz/Schniz/fnm/releases/download/v${FNM_VERSION}/fnm-linux.zip" \
#   ; unzip fnm-linux.zip \
#   ; chmod +x fnm \
#   ; mkdir -p $FNM_HOME \
#   ; mv fnm $FNM_HOME \
#   ; rm fnm-linux.zip

  ; cargo install fnm

  RUN set -eux \
  ; echo 'eval "$(fnm env --use-on-cd)"' \
      >> $HOME/.bashrc \
  ; echo 'eval "$(fnm env --use-on-cd)"' \
      >> $HOME/.zshrc \
  ; echo 'fnm env --use-on-cd | source' \
      >> $HOME/.config/fish/config.fish

  RUN set -eux \
#   ; export PATH=$FNM_HOME:$PATH \
  ; fnm install 17 \
      --node-dist-mirror https://mirrors.tuna.tsinghua.edu.cn/nodejs-release \
  ; fnm install 16 \
      --node-dist-mirror https://mirrors.tuna.tsinghua.edu.cn/nodejs-release \
  ; fnm alias 16 default

  RUN set -eux \

  ; eval $(fnm env --shell bash) \

  ; npm i -g pnpm \

  ; pnpm i -g pnpm \
  ; pnpm i -g npm \
  ; pnpm i -g yarn \

  ; pnpm i -g nnrm \
  # ; nnrm use taobao

  # node-inspector
  ; pnpm i -g npm-check \
  ; pnpm i -g node-gyp \

  ; pnpm i -g supervisor nodemon forever pm2 \
  ; pnpm i -g serve http-server

  # pnpm i -g lerna autod
  # pnpm i -g json-server
