# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  API_KEY: APIm82yMo4V3Nfg
  API_SECRET: VoZ3tfOf3fAEIPbQj64RffPAO5m2On9Tkoh3yMy8VpxC

tasks:

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  get-bin:
    cmds:
      - |-
        mkdir -p ../tmp \
        && mkdir -p ../bin \
        && rm -rf ../bin \
        && rm -rf ../tmp \
        && mkdir -p ../tmp \
        && mkdir -p ../bin
      - |-
        cd ../tmp \
        && aria2c https://hub.fastgit.xyz/livekit/livekit-cli/releases/download/v1.1.0/livekit-cli_1.1.0_linux_amd64.tar.gz \
        && tar xvf livekit-cli_1.1.0_linux_amd64.tar.gz \
        && aria2c https://hub.fastgit.xyz/livekit/livekit/releases/download/v1.1.2/livekit_1.1.2_linux_amd64.tar.gz \
        && tar xvf livekit_1.1.2_linux_amd64.tar.gz \
        && mv livekit-cli ../bin \
        && mv livekit-server ../bin
      - rm -rf ../tmp
      - |-
        chmod +x ../bin/livekit-cli \
        && chmod +x ../bin/livekit-cli

  generate-keys:
    cmds:
      # - ../bin/livekit-server generate-keys

      # -- fish
      # - for l in (../bin/livekit-server generate-keys); echo $l | sed -e 's/^API.*:/\U&/' | awk '{print $1"_"$2" "$3}'; end
      # - for l in (../bin/livekit-server generate-keys); echo $l | sed -e 's/^API.*:/\U&/' | awk '{print $1"_"$2" "$3}'; end | string join '\n'
      # - sed "/^  API_.*\$/{N;s/.*/"(echo "  API_:\n  API_:")"/}" Taskfile.yaml
      # - sed "/^  API_.*\$/{N;s/.*/"(for l in (../bin/livekit-server generate-keys); echo $l | sed -e 's/^API.*:/\U&/' | awk '{print "  "$1"_"$2" "$3}'; end | string join '\n')"/}" Taskfile.yaml
      # - sed -i "/^  API_.*\$/{N;s/.*/"(for l in (../bin/livekit-server generate-keys); echo $l | sed -e 's/^API.*:/\U&/' | awk '{print "  "$1"_"$2" "$3}'; end | string join '\n')"/}" Taskfile.yaml

      # -- bash
      # - IFS=''; for l in $(../bin/livekit-server generate-keys); do echo $l | sed -e 's/^API.*:/\U&/' | awk '{print $1"_"$2" "$3}'; done
      # - IFS=''; for l in $(../bin/livekit-server generate-keys); do echo $l | sed -e 's/^API.*:/\U&/' | awk '{print $1"_"$2" "$3}'; done | xargs echo | sed -e 's/ API_/\\nAPI/g'
      # - IFS=''; for l in $(../bin/livekit-server generate-keys); do echo $l | sed -e 's/^API.*:/\U&/' | awk '{print $1"_"$2" "$3}'; done | xargs echo | sed -e 's/ API_/\\n  API/g' -e 's/^API_/  API_/g'
      # - sed '/^  API_.*$/{N;s/.*/'"$(echo 123)"'/}' Taskfile.yaml
      # - sed '/^  API_.*$/{N;s/.*/'"$(echo "  API_KEY: APIqQMv6yfiPTa8\n  API_SECRET: XYa8zAKYhrrDqbnVYA4Jv5Og5dSRlOFxdWGd1KFTfsX")"'/}' Taskfile.yaml
      # - VAR=$(IFS=''; for l in $(../bin/livekit-server generate-keys); do echo $l | sed -e 's/^API.*:/\U&/' | awk '{print $1"_"$2" "$3}'; done | xargs echo | sed -e 's/ API_/\\n  API_/g' -e 's/^API_/  API_/g'); sed '/^  API_.*$/{N;s/.*/'"${VAR}"'/}' Taskfile.yaml

      - VAR=$(IFS=''; for l in $(../bin/livekit-server generate-keys); do echo $l | sed -e 's/^API.*:/\U&/' | awk '{print $1"_"$2" "$3}'; done | xargs echo | sed -e 's/ API_/\\n  API_/g' -e 's/^API_/  API_/g'); sed '/^  API_.*$/{N;s/.*/'"${VAR}"'/}' Taskfile.yaml > Taskfile.tmp.yaml
      - mv ./Taskfile.tmp.yaml ./Taskfile.yaml

  dev-server:
    cmds:
      - '../bin/livekit-server --keys="{{.API_KEY}}: {{.API_SECRET}}" --dev'

  create-room:
    cmds:
      - ../bin/livekit-cli create-room --api-key={{.API_KEY}} --api-secret={{.API_SECRET}} --name myroom

  list-rooms:
    cmds:
      - ../bin/livekit-cli list-rooms --api-key={{.API_KEY}} --api-secret={{.API_SECRET}}

  delete-room:
    cmds:
      - ../bin/livekit-cli delete-room --api-key={{.API_KEY}} --api-secret={{.API_SECRET}} --room myroom

  join-room:
    cmds:
      - ../bin/livekit-cli join-room --api-key={{.API_KEY}} --api-secret={{.API_SECRET}} --room myroom --identity cotfea
