version: '3'

includes:
  helper: ~/.taskfilehub/hubs/helper.yml
  opam-package-proxy: ./opam-package-proxy.yml

vars:
  # default
  ocaml_version: 5.0.0

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  install-pre:
    cmds:
      - nix-env -i
          gnumake gcc-wrapper
          diffutils patch
          rsync mercurial darcs
          gawk bzip2

  install-opam-ocaml:
    cmds:
      - nix-env -i opam
      # ocaml

  clone-opam-repo:
    vars:
      # https://mirrors.sjtug.sjtu.edu.cn/git/opam-repository.git
      # https://ghproxy.com/https://github.com/ocaml/opam-repository.git
      # dont use: https://gitclone.com/github.com/ocaml/opam-repository.git
      DEFAULT_REPO: https://ghproxy.com/github.com/ocaml/opam-repository.git
    cmds:
      - git clone
          -b master --depth=1
          {{.DEFAULT_REPO}}
          ~/.opam-repository

  init-opam:
    deps:
      - clone-opam-repo
    cmds:
      - task: opam-package-proxy:all
      # --shell-setup
      # --bare
      - opam init
          --disable-sandboxing
          -y default ~/.opam-repository
      # - opam switch create {{.ocaml_version}}
      - opam update
      - opam switch create {{.ocaml_version}}+flambda+nffa
          ocaml-variants.{{.ocaml_version}}+options
          ocaml-option-flambda
          ocaml-option-no-flat-float-array

  opam-env:
    cmds:
      - task: helper:fn-echo-in-profile
        vars:
          # raws: eval $(opam env --switch=default)
          raws: eval $(opam env --switch={{.ocaml_version}}+flambda+nffa)

  # opam-package-proxy-before:
  #   cmds:
  #     - cd ~/.opam/repo
  #       ; tar xvf default.tar.gz

  # opam-package-proxy-post:
  #   cmds:
  #     - cd ~/.opam/repo
  #       ; rm -rf ./default.tar.gz
  #       ; tar zcvf default.tar.gz default
  #       ; rm -rf ./default

  opam-download-command:
    cmds:
      - cp ./opam_download_command ~/.local/bin
      - '
        sed -i "/download-jobs/adownload-command: [
        \n  \"opam_download_command\"
        \n  \"%{out}%\"
        \n  \"%{url}%\"
        \n]" ~/.opam/config
        '
      # download-command: [
      #   "download_command"
      #   "%{out}%"
      #   "%{url}%"
      # ]
      # global config:
      # axel -o %{out}% %{url}%
      # opam install --download-only -y dune

  install-pkgs:
    cmds:
      # js_of_ocaml js_of_ocaml-compiler js_of_ocaml-lwt js_of_ocaml-ppx
      - bash -lc '
        opam option --global depext=false
        ; opam install -y
            dune utop ocamlfind ocaml-lsp-server
            base core stdio
            domainslib
        '

  install-all:
    deps:
      - install-pre
    cmds:
      - task: install-opam-ocaml
      - task: init-opam
      - task: opam-env
      - task: opam-download-command

      - task: install-pkgs
