name: 01_base_dev_node

on:
  workflow_dispatch:

jobs:

  earthly:
    name: 01_base_dev_node
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:

      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - uses: earthly/actions-setup@v1
        with:
          version: "latest" # or pin to an specific version, e.g. "v0.6.10"
      - uses: actions/checkout@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: what version is installed?
        run: earthly --version

      - name: run the earthly hello world
        run: earthly github.com/earthly/hello-world:main+hello

      - name: base-image
        run: cd src && earthly +base-image

      - name: docker images
        run: docker images
