name: 01_base_dev_node

on:
  workflow_dispatch:

jobs:

  earthly:
    name: 01_base_dev_node
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:

      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - uses: earthly/actions-setup@v1
        with:
          version: "latest" # or pin to an specific version, e.g. "v1.6.10"
      - uses: actions/checkout@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: what version is installed?
        run: earthly --version

      - name: run the earthly hello world
        run: earthly github.com/earthly/hello-world:main+hello

      -
        name: replace fastgit to github
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '(hub|download).fastgit.(org|xyz)'
          replace: "github.com"
          include: "**/Earthfile"
          regex: true

      -
        name: replace fastgit to github
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'raw.fastgit.(org|xyz)'
          replace: "raw.githubusercontent.com"
          include: "**/Earthfile"
          regex: true

      - name: before build
        run: cp ./src/Earthfile.sample ./src/Earthfile

      - name: build base-image
        run: earthly --push ./src+base-image

      - name: build dev-image
        run: earthly --push ./src+dev-image

      - name: build go-image
        run: earthly --push ./src+go-image

      - name: build node-image
        run: earthly --push ./src+node-image

      - name: build wasm-image
        run: earthly --push ./src+wasm-image

      - name: build ocaml-image
        run: earthly --push ./src+ocaml-image

      - name: build sdkman-image
        run: earthly --push ./src+sdkman-image

      - name: after build
        run: rm ./src/Earthfile

      - name: docker tag and push
        run: |
          docker images
          docker tag mooxe/base mooxe/base:0.1.10
          docker tag mooxe/dev mooxe/dev:0.1.10
          docker tag mooxe/go mooxe/go:0.1.10
          docker tag mooxe/node mooxe/node:0.1.10
          docker tag mooxe/wasm mooxe/wasm:0.1.10
          docker tag mooxe/ocaml mooxe/ocaml:0.1.10
          docker tag mooxe/sdkman mooxe/sdkman:0.1.10
          docker images
          docker push mooxe/base:0.1.10
          docker push mooxe/dev:0.1.10
          docker push mooxe/go:0.1.10
          docker push mooxe/node:0.1.10
          docker push mooxe/wasm:0.1.10
          docker push mooxe/ocaml:0.1.10
          docker push mooxe/sdkman:0.1.10

      -
        name: Inspect
        run: |
          docker buildx imagetools inspect mooxe/base
          docker buildx imagetools inspect mooxe/dev
          docker buildx imagetools inspect mooxe/go
          docker buildx imagetools inspect mooxe/node
          docker buildx imagetools inspect mooxe/wasm
          docker buildx imagetools inspect mooxe/ocaml
          docker buildx imagetools inspect mooxe/sdkman
