version: '3'

includes:
  helper: ~/.taskfilehub/hubs/helper.yml

vars:
  version_node: 18.12.1
  nix_node_global_path:
    /nix/store/$(
      ls /nix/store
      | grep -e "nodejs-{{.version_node}}$"
      | sed -n '1p'
    )/bin
  registry_mirror: https://registry.npm.taobao.org

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  update-npm:
    cmds:
      - npm i -g
          --no-fund
          --registry={{.registry_mirror}}
          npm

  install-use-nnrm:
    vars:
      nix_node_global_path:
        sh: echo {{.nix_node_global_path}}
    cmds:
      - npm i -g
          --registry={{.registry_mirror}}
          nnrm
      - export PATH=$PATH:{{.nix_node_global_path}}
        ; nnrm use taobao

  install-yarn:
    vars:
      nix_node_global_path:
        sh: echo {{.nix_node_global_path}}
    cmds:
      - npm i -g yarn

      # node-inspector
      # npm-check

      # lerna autod
      # json-server

      - export PATH=$PATH:{{.nix_node_global_path}}
        ; yarn global add pnpm
            taze node-gyp
            serve http-server
            supervisor nodemon forever pm2

  node-global-env:
    vars:
      nix_node_global_path:
        sh: echo {{.nix_node_global_path}}
      yarn_global_path: /usr/local/share/.config/yarn/global/node_modules/.bin
      PATH: $PATH:{{.nix_node_global_path}}:{{.yarn_global_path}}
    cmds:
      - task: helper:fn-env-kv
        vars:
          env_key: PATH
          env_value: '{{.PATH}}'

  cli-version:
    cmds:
      - echo "node $(node --version)"
      - echo "npm $(npm --version)"
      - echo "yarn $(yarn --version)"
      - echo "pnpm $(pnpm --version)"
      - echo "bun $(bun --version)"

  install-all:
    cmds:
      - nix-env -i nodejs bun
      - task: update-npm
      - task: node-global-env

      - task: install-use-nnrm
      - task: install-yarn
