VERSION 0.6

VERSION:
  COMMAND
  ENV DENO_VERSION=1.22.3

ENV:
  COMMAND
  ENV DENO_DIR /deno-dir/
  ENV DENO_INSTALL_ROOT /usr/local

bin:
  LOCALLY
  DO +VERSION
  ARG BIN_IMAGE=denoland/deno:bin-${DENO_VERSION}

  FROM ${BIN_IMAGE}
  SAVE ARTIFACT /deno

INSTALL_DVM:
  COMMAND

  DO +VERSION

  ENV DVM_VERSION=1.8.0

  RUN set -eux \
  ; cargo install dvm --version $DVM_VERSION \
  ; dvm install $DENO_VERSION
  # ; dvm use $DENO_VERSION

INSTALL:
  COMMAND

  BUILD +bin

  DO +VERSION
  DO +ENV

  RUN set -eux \

  # ; addgroup --gid 1000 deno \
  # ; adduser --uid 1000 \
  #     --disabled-password deno \
  #     --ingroup deno \

  ; useradd --uid 1993 --user-group deno \
  ; mkdir /deno-dir/ \
  ; chown deno:deno /deno-dir/

  ARG DENO_VERSION
  ENV DENO_VERSION=${DENO_VERSION}

  COPY +bin/deno /bin/deno
