VERSION 0.6

VERSION:
  COMMAND
  ENV DENO_VERSION=1.24.1

ENV:
  COMMAND
  ENV DENO_DIR /deno-dir/
  ENV DENO_INSTALL_ROOT /usr/local

bin:
  LOCALLY
  DO +VERSION
  ARG BIN_IMAGE=denoland/deno:bin-${DENO_VERSION}

  FROM ${BIN_IMAGE}
  SAVE ARTIFACT /deno

FIX_OPENSSLSYS_BEFORE_INSTALL:
  COMMAND
  RUN set -eux \
  ; apt remove -y \
      pkg-config build-essential libssl-dev:amd64 librust-openssl-sys-dev:amd64 \
  ; apt install -y \
      pkg-config build-essential libssl-dev librust-openssl-sys-dev \
  ; apt-mark auto pkg-config build-essential

INSTALL_DVM:
  COMMAND

  DO +VERSION

  ENV DVM_VERSION=1.8.6

  DO +FIX_OPENSSLSYS_BEFORE_INSTALL

  RUN set -eux \
  ; cargo install dvm --version $DVM_VERSION \
  ; dvm install $DENO_VERSION
  # ; dvm use $DENO_VERSION

INSTALL:
  COMMAND

  BUILD +bin

  DO +VERSION
  DO +ENV

  RUN set -eux \

  # ; addgroup --gid 1000 deno \
  # ; adduser --uid 1000 \
  #     --disabled-password deno \
  #     --ingroup deno \

  ; useradd --uid 1993 --user-group deno \
  ; mkdir /deno-dir/ \
  ; chown deno:deno /deno-dir/

  ARG DENO_VERSION
  ENV DENO_VERSION=${DENO_VERSION}

  COPY +bin/deno /bin/deno

BUN:
  COMMAND

  ENV BUN_VERSION=0.1.6
  ENV SWS_FILE_DIRNAME=bun-linux-x64
  ENV SWS_ZIP_FILE=$SWS_FILE_DIRNAME.zip

  RUN set -eux \
  ; aria2c "https://hub.fastgit.xyz/oven-sh/bun/releases/download/bun-v${BUN_VERSION}/${SWS_ZIP_FILE}" \
  ; unzip $SWS_ZIP_FILE \
  ; cp $SWS_FILE_DIRNAME/bun $HOME/.local/bin/bun \
  ; rm -rf ./${SWS_FILE_DIRNAME}*
